//@version=4
//
// ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ 
//  -----------------------------------------------------------------------------
//  Copyright 2019 Mauricio Pimenta | exit490
//  SuperTrend with Trailing Stop Loss script may be freely distributed under the MIT license.
//
//  Permission is hereby granted, free of charge, 
//  to any person obtaining a copy of this software and associated documentation files (the "Software"), 
//  to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, 
//  publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
//  subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
//  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
//  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//  -----------------------------------------------------------------------------
//
//  Authors:  @exit490
//  Revision: v1.1.0
//  Date:     5-Aug-2019
//
//  Description
//  ===========
//  SuperTrend is a moving stop and reversal line based on the volatility (ATR).
//  The strategy will ride up your stop loss when price movemented according with input trailing percent.
//  The strategy will close your operation when the market price crossed the stop loss.
//  The strategy will close operation when the line based on the volatility will crossed
//
//  The strategy has the following parameters:
//
//  INITIAL STOP LOSS - Where can isert the value to first stop.
//  POSITION TYPE - Where can to select trade position.
//  ATR PERIOD - To select number of bars back to execute calculation
//  ATR MULTPLIER - To add a multplier factor on volatility
//  BACKTEST PERIOD - To select range.
//  
//  -----------------------------------------------------------------------------
//  Disclaimer:
//    1. I am not licensed financial advisors or broker dealers. I do not tell you 
//       when or what to buy or sell. I developed this software which enables you 
//       execute manual or automated trades multiple trades using TradingView. The 
//       software allows you to set the criteria you want for entering and exiting 
//       trades.
//    2. Do not trade with money you cannot afford to lose.
//    3. I do not guarantee consistent profits or that anyone can make money with no 
//       effort. And I am not selling the holy grail.
//    4. Every system can have winning and losing streaks.
//    5. Money management plays a large role in the results of your trading. For 
//       example: lot size, account size, broker leverage, and broker margin call 
//       rules all have an effect on results. Also, your Take Profit and Stop Loss 
//       settings for individual pair trades and for overall account equity have a 
//       major impact on results. If you are new to trading and do not understand 
//       these items, then I recommend you seek education materials to further your
//       knowledge.
//
//    YOU NEED TO FIND AND USE THE TRADING SYSTEM THAT WORKS BEST FOR YOU AND YOUR 
//    TRADING TOLERANCE.
//
//    I HAVE PROVIDED NOTHING MORE THAN A TOOL WITH OPTIONS FOR YOU TO TRADE WITH THIS PROGRAM ON TRADINGVIEW.
//    
//    I accept suggestions to improve the script.
//    If you encounter any problems I will be happy to share with me.
//  -----------------------------------------------------------------------------
//
// ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ //

study("SUPERTREND ATR WITH ANALYTICS", overlay=true, precision = 8)

parameterSection = input(title = "═════════════ STRATEGY ═════════════", defval = true, type = input.bool)
// === INPUT TO SELECT POSITION ===
positionType = input(defval="SHORT", title="Position Type", options=["LONG", "SHORT"])
takeProfit = input(defval = 3.0, minval = 0.0, title="Take Profit")

// === INPUT TO SELECT BARS BACK
barsBack = input(title="ATR Period", defval=1)

// === INPUT TO SELECT MULTPLIER FACTOR 
multplierFactor = input(title="ATR multiplier", step=0.1, defval=3.0)

//
// ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ //

// LOGIC TO FIND DIRECTION WHEN THERE IS TREND CHANGE ACCORDING VOLATILITY
atr = multplierFactor * atr(barsBack)

longStop = hl2 - atr
longStopPrev = nz(longStop[1], longStop)
longStop := close[1] > longStopPrev ? max(longStop, longStopPrev) : longStop

shortStop = hl2 + atr
shortStopPrev = nz(shortStop[1], shortStop)
shortStop := close[1] < shortStopPrev ? min(shortStop, shortStopPrev) : shortStop

direction = 1
direction := nz(direction[1], direction)
direction := direction == -1 and close > shortStopPrev ? 1 : direction == 1 and close < longStopPrev ? -1 : direction

longColor = color.blue
shortColor = color.blue

var valueToPlot = 0.0
var colorToPlot = color.white

if (direction == 1)
    valueToPlot := longStop
    colorToPlot := color.green
else
    valueToPlot := shortStop
    colorToPlot := color.red

isLong() => positionType == "LONG" ? true : false
isShort() => positionType == "SHORT" ? true : false
takeProfit := isShort() ? takeProfit * -1 : takeProfit
//
// ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ //

// === DRAWING SHAPES AND SHAPES

plot(valueToPlot == 0.0 ? na : valueToPlot, title="LINE", linewidth=2, color=colorToPlot)

plotshape(direction == 1 and direction[1] == -1 ? longStop : na, title="UPTREND", style=shape.labelup, location=location.absolute, size=size.normal, text="UPTREND", transp=0, textcolor = color.white, color=color.green, transp=0)
plotshape(direction == -1 and direction[1] == 1 ? shortStop : na, title="DOWNTREND", style=shape.labeldown, location=location.absolute, size=size.normal, text="DOWNTREND", transp=0, textcolor = color.white, color=color.red, transp=0)

// === ANALYTICS

var closeInLastTrendReversal = 0.0
var majorPercentInTrend = 0.0
var minorPercentInTrend = 0.0
var majorCloseInTrend = 0.0
var minorCloseInTrend = 30000.0
var upTrendOccurrences = 0
var totalMajorPercent = 0.0
var totalMinorPercent = 0.0
var targetHit = 0

upTrendConditional = direction == 1 and direction[1] == -1
downTrendConditional = direction == -1 and direction[1] == 1

if isLong() and downTrendConditional
    for i = 1 to 300
        majorCloseInTrend := max(high[i], majorCloseInTrend)
        minorCloseInTrend := min(minorCloseInTrend, low[i])
        if direction[i] == 1 and direction[i+1] == -1
            closeInLastTrendReversal := close[i]
            break
    
    majorPercentInTrend := (majorCloseInTrend - closeInLastTrendReversal) / closeInLastTrendReversal * 100.00
    minorPercentInTrend := (minorCloseInTrend - closeInLastTrendReversal) / closeInLastTrendReversal * 100.00

    if(majorPercentInTrend > takeProfit)
        targetHit := targetHit + 1

    upTrendOccurrences := upTrendOccurrences + 1

    totalMajorPercent := nz(totalMajorPercent + majorPercentInTrend)
    totalMinorPercent := nz(totalMinorPercent + minorPercentInTrend)

    majorCloseInTrendText = '\nMAJOR_%: ' + tostring(majorPercentInTrend)
    minorCloseInTrendText =  '\nMINOR_%: ' + tostring(minorPercentInTrend)
    avgMajorPercentInTrendText = '\n\nAVG MAJOR_%: ' + tostring(totalMajorPercent/upTrendOccurrences)
    avgMinorPercentInTrendText = '\nAVG MINOR_%: ' + tostring(totalMinorPercent/upTrendOccurrences)
    upTrendOccurrencesText = '\n\nUPTRENDS: ' + tostring(upTrendOccurrences)
    targetHitText = '\nHIT ' + tostring(takeProfit) + '%: ' + tostring(targetHit)
    targetHitPercentText = '\nHIT_%: ' + tostring((targetHit/upTrendOccurrences) * 100) 

    infoText = 'ANALYTICS\n'  + majorCloseInTrendText + minorCloseInTrendText + avgMajorPercentInTrendText + avgMinorPercentInTrendText + upTrendOccurrencesText + targetHitText + targetHitPercentText
    label.new(bar_index, close + close*-0.01 , infoText, color=color.blue, textcolor=color.white, style=label.style_labelup, size=size.normal, yloc=yloc.price)

if isShort() and upTrendConditional
    for i = 1 to 300
        majorCloseInTrend := max(high[i], majorCloseInTrend)
        minorCloseInTrend := min(minorCloseInTrend, low[i])
        if direction[i] == -1 and direction[i+1] == 1
            closeInLastTrendReversal := close[i]
            break
    
    majorPercentInTrend := (majorCloseInTrend - closeInLastTrendReversal) / closeInLastTrendReversal * 100.00
    minorPercentInTrend := (minorCloseInTrend - closeInLastTrendReversal) / closeInLastTrendReversal * 100.00

    if(minorPercentInTrend < takeProfit)
        targetHit := targetHit + 1

    upTrendOccurrences := upTrendOccurrences + 1

    totalMajorPercent := nz(totalMajorPercent + majorPercentInTrend)
    totalMinorPercent := nz(totalMinorPercent + minorPercentInTrend)

    majorCloseInTrendText = '\nMAJOR_%: ' + tostring(majorPercentInTrend)
    minorCloseInTrendText =  '\nMINOR_%: ' + tostring(minorPercentInTrend)
    avgMajorPercentInTrendText = '\n\nAVG MAJOR_%: ' + tostring(totalMajorPercent/upTrendOccurrences)
    avgMinorPercentInTrendText = '\nAVG MINOR_%: ' + tostring(totalMinorPercent/upTrendOccurrences)
    upTrendOccurrencesText = '\n\nUPTRENDS: ' + tostring(upTrendOccurrences)
    targetHitText = '\nHIT ' + tostring(takeProfit) + '%: ' + tostring(targetHit)
    targetHitPercentText = '\nHIT_%: ' + tostring((targetHit/upTrendOccurrences) * 100) 

    infoText = 'ANALYTICS\n'  + majorCloseInTrendText + minorCloseInTrendText + avgMajorPercentInTrendText + avgMinorPercentInTrendText + upTrendOccurrencesText + targetHitText + targetHitPercentText
    label.new(bar_index, high + high*0.015 , infoText, color=color.blue, textcolor=color.white, style=label.style_labeldown, size=size.normal, yloc=yloc.price)


majorCloseInTrend := 0.0
minorCloseInTrend := 30000.0

alertcondition(upTrendConditional, title="Open Position", message="Open Position")
alertcondition(downTrendConditional, title="Close Position", message="Close Position")
//lapos_x = timenow + round(change(time)*30)
//lapos_y = highest(20)
//avgText = tostring(totalMajorPercent/upTrendOccurrences)  + '\n' + tostring(totalMinorPercent/upTrendOccurrences) + '\n' + tostring(targetHit) +'\n' + tostring(upTrendOccurrences)
//avgLabel :=  label.new(lapos_x, lapos_y, avgText, color=color.blue, textcolor=color.white, style=label.style_labeldown, xloc=xloc.bar_time, size=size.large)

